[package]
name = "rush_sync"
version = "0.1.7"
edition = "2021"

[dependencies]
crossterm = "0.27"
ratatui = "0.24"
unicode-segmentation = "1.10"

serde = { version = "1.0", features = ["derive"] }
toml = "0.8"

env_logger = "0.10"
log = "0.4" 
lazy_static = "1.4"
strip-ansi-escapes = "0.1.1"

tokio = { version = "1.36", features = ["full"] }
futures = "0.3"

dirs = "5.0" 

serde_json = "1.0"


# Optional aber nützlich
#anyhow = "1.0"           # Fehlerbehandlung
#thiserror = "1.0"        # Eigene Fehlertypen

#[features]
#default = ["input"]       # Standard-Features
#input = []               # Feature für Input-Funktionalität