[package]
name = "rush_sync"
version = "0.1.8"
edition = "2021"

[dependencies]
crossterm = "0.27"
ratatui = "0.24"
unicode-segmentation = "1.10"

serde = { version = "1.0", features = ["derive"] }
toml = "0.8"

env_logger = "0.10"
log = "0.4"
lazy_static = "1.4"
strip-ansi-escapes = "0.1.1"

tokio = { version = "1.36", features = ["full"] }

serde_json = "1.0"

rust-embed = "6.8"

[lints.clippy]
module_inception = "allow"
